### ISSUE TITLE
Some minor suggestions

### ISSUE THREAD

**Issue by greyelf** [LockeBirdsey/harlowechatapp#1]
Again great work.

1) Due to how Harlowe implements the Visual Effect associated with its Passage Transition process any  **block** based HTML element included within a Passage will be excluded from that effect.

eg. Block based elements (like your `<section>`) are shown instantly where as the elements generated by Harlowe itself will fade in.

To overcome this issue you need to change the the CSS **display** property of the effected elements to **inline-block**. In the cases where you aren't setting a specific **width** property value to an element but you want to them to horizontally fill the parent you will need to assign a 100%
eg. the following extends two of your own selectors.
`
.module {
    display: inline-block;
    /* other property settings go here */
}
.discussion .avatar img {
    display: inline-block;
    width: 100%;
}
`

2) The naming of the first Passage shown to the end-user. eg. your "Untitled Passage"

Generally in a TWEE project this Passage would be named **Start** because that is the name:
a) used within the Twine Cookbook.
b) that TWEE compilers like TweeGo expect unless told otherwise.
c) automatically assigned that passage in the old Twine 1.x application.

**Comment by LockeBirdsey** [comment]
Many thanks for the comments.
Both issues are resolved now and tested in the story I pulled this from.
